[package]
name = "monitr"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
anyhow = "1.0.97"
env_logger = "0.11.8"
log = "0.4.27"
tokio = "1.44.1"
prometheus = "0.14.0"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
